"""Exception raised for errors in the processing of data."""

from connector.src.custom.exceptions.gti_base_error import GTIBaseError


class GTIProcessingError(GTIBaseError):
    """Exception raised for errors in the processing of data."""

    ...
